In [17]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import make_blobs

In [18]:
centers = [[-5,2],[-2,-2],[1,2],[5,-2]]
X_train, y_train = make_blobs(n_samples=2000, centers=centers, cluster_std=1.0,random_state=30) #Creates data points grouped around a number of cluster centers with Gaussian (normal) distribution.

In [19]:
# Using basic approach
model = Sequential( # Create model
    [
        Dense(25,activation = 'relu'), # hidden layers
        Dense(15,activation = 'relu'),
        Dense(4,activation = 'softmax') # output layer
    ]
)

model.compile(loss = tf.keras.losses.SparseCategoricalCrossentropy(), optimizer = tf.keras.optimizers.Adam())
model.fit(X_train,y_train, epochs = 10)




Epoch 1/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.9022
Epoch 2/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.7853
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3121
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.1617
Epoch 5/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.1037
Epoch 6/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0806
Epoch 7/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0679
Epoch 8/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0562
Epoch 9/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0506
Epoch 10/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0419


In [21]:
p_nonpreferred = model.predict(X_train)
print(p_nonpreferred [:2])
print("largest value", np.max(p_nonpreferred), "smallest value", np.min(p_nonpreferred))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[6.9962293e-03 3.0204621e-03 9.6919930e-01 2.0783920e-02]
 [9.9143165e-01 7.9613142e-03 6.0103292e-04 6.0274574e-06]]
largest value 0.99999815 smallest value 5.452639e-09


In [22]:
# Using linear activation method to lessen numerical deviation due to floating points

preferred_model = Sequential(
    [
        Dense(25,activation = 'relu'),
        Dense(15,activation = 'relu'),
        Dense(4,activation = 'linear')
    ]
)

preferred_model.compile(loss = tf.keras.losses.SparseCategoricalCrossentropy(), optimizer = tf.keras.optimizers.Adam())
preferred_model.fit(X_train,y_train,epochs = 10)


Epoch 1/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 5.3630
Epoch 2/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.2387
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.2379
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.2289
Epoch 5/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.1726
Epoch 6/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.1600
Epoch 7/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.1200
Epoch 8/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.1044
Epoch 9/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.1763
Epoch 10/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0874


In [23]:
# Must send this version through a softmax because we recieve numbers instead of probablity for our values
p_preferred = preferred_model.predict(X_train)
print(f"two example output vectors:\n {p_preferred[:2]}")
print("largest value", np.max(p_preferred), "smallest value", np.min(p_preferred))

# Now we actually send it through a softmax
sm_preferred = tf.nn.softmax(p_preferred).numpy()
print(f"two example output vectors:\n {sm_preferred[:2]}")
print("largest value", np.max(sm_preferred), "smallest value", np.min(sm_preferred))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
two example output vectors:
 [[-0.43425214 -0.45135114 -0.74609387 -0.4925706 ]
 [-0.92744195 -0.5667276  -0.76207674 -1.8340701 ]]
largest value 0.4028529 smallest value -3.5123703
two example output vectors:
 [[0.27333662 0.26870257 0.20010902 0.25785193]
 [0.24887626 0.3569766  0.29363018 0.10051708]]
largest value 0.53983915 smallest value 0.044836994


In [24]:
# Select the most likely cateogry using np.argmax

for i in range(10):
    print( f"{p_preferred[i]}, category: {np.argmax(p_preferred[i])}")

[-0.43425214 -0.45135114 -0.74609387 -0.4925706 ], category: 0
[-0.92744195 -0.5667276  -0.76207674 -1.8340701 ], category: 1
[-0.70841503 -0.45065448 -0.61833626 -1.4073251 ], category: 1
[-0.41255277  0.08262073 -0.24769172 -0.26607084], category: 1
[-0.6687454 -1.0726736 -1.0486357 -1.3427936], category: 0
[-0.37274617 -0.6136846  -0.85777664 -0.56558806], category: 0
[-0.53562725  0.02696533 -0.35257933 -0.23563902], category: 1
[-1.0670258  -0.77977276 -0.89167464 -2.2328188 ], category: 1
[-0.48395655  0.1156655  -0.25879064 -0.31407252], category: 1
[-0.8474314 -0.6085786 -0.9147182 -0.6854592], category: 1
